import {
  sendWelcomeEmail,
  sendInvitationEmail,
  sendTestEmail,
  registerWithInvitation,
  validateInvitation,
  sendPasswordResetInstructions,
  sendModificationRequestEmail,
  getAttendeeForModification,
  updateAttendeeRegistration,
  sendNewUserRequestEmail,
  createNotification,
  generateInvitations,
  createSlotRequestsWithUsers,
  uploadFile,
  deleteFile,
  generateOTP,
  createOTP,
  verifyOTP,
  sendOTPEmail,
  sendOTP,
  createUserProfile,
  createUserDirectly,
  deleteUserCompletely,
  verifyTurnstileToken,
  updateIsReset,
  updateUserAccess,
  updateEmailTemplateStatus,
  sendUserReminderEmail,
  sendTrophyAwardEmail
} from './supabaseFunctions.js';

// Export all functions
export {
  sendWelcomeEmail,
  sendInvitationEmail,
  sendTestEmail,
  registerWithInvitation,
  validateInvitation,
  sendPasswordResetInstructions,
  sendModificationRequestEmail,
  getAttendeeForModification,
  updateAttendeeRegistration,
  sendNewUserRequestEmail,
  createNotification,
  generateInvitations,
  createSlotRequestsWithUsers,
  uploadFile,
  deleteFile,
  generateOTP,
  createOTP,
  verifyOTP,
  sendOTPEmail,
  sendOTP,
  createUserProfile,
  createUserDirectly,
  deleteUserCompletely,
  verifyTurnstileToken,
  updateIsReset,
  updateUserAccess,
  updateEmailTemplateStatus,
  sendUserReminderEmail,
  sendTrophyAwardEmail
};
  
  